### ISSUE TITLE
QueryBuilder: Support for transaction?

### ISSUE THREAD

**Issue by mradlmaier** [jesperborgstrup/buzzingandroid#5]
I need to update 2 tables which are related through a foreign key column. Is it possible to use the QueryBuilder class with transactions?

**Comment by jesperborgstrup** [comment]
As I see it, the `QueryBuilder` doesn't have anything to do with transactions, that is instead the responsibility of the `SQLiteDatabase` class (https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html) with its `beginTransaction*()` and endTransaction()` methods.
